source_folder: ../../processed/java_antlr_8_2/java/
classifier_type: rf
mode: snapshot
features:
  - "starts"
  - "paths"
seed: 239
test_size: 1
feature_count: 10000
params:
  n_estimators: 300
  n_jobs: -1
  min_samples_leaf: 1
  min_samples_split: 2
  max_features: 'sqrt'
  max_depth: 60
  random_state: 239
