name: authorship-detection
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - numpy=1.16.2
  - pandas=0.24.2
  - parse=1.11.1
  - python=3.6.8
  - pytorch=1.0.1
  - pyyaml=5.1
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - yaml=0.1.7
