source_folder: "../processed/gcjpy"
mutual_info_file: "mutual_info/all_py_scores.numpy"
features:
  - "paths"
  - "starts"
label_position: 3
seed: 239
test_size: 2
feature_count: 14000
params:
  n_estimators: 500
  n_jobs: -1
  min_samples_leaf: 1
  min_samples_split: 2
  max_features: 'sqrt'
  random_state: 239