source_folder: "../processed/gcjpy"
features:
  - "paths"
  - "starts"
label_position: 3
seed: 239
test_size: 2
n_classes: 25
n_runs: 5
params:
  n_estimators: 10
  n_jobs: -1
  min_samples_leaf: 1
  min_samples_split: 2
  max_features: 'sqrt'
  random_state: 239