classifier_type: caliskan
feature_count: 2500
max_count: 20000
min_count: 1000
mode: time
params:
  max_features: log2
  min_samples_leaf: 1
  min_samples_split: 2
  n_estimators: 100
  n_jobs: -1
  random_state: 239
seed: 239
source_folder: ../gitminer/out/Osmand
time_folds: 10
