mutual_info_file: "mutual_info/timesplit_20.numpy"
source_folder: "/home/egor/Work/codestyle/code/code2vec/dataset/idea-changes/"
entities_folder: "/home/egor/Work/codestyle/code/code2vec/dataset/idea-changes/creations/entity/"
change_ids_folder: "/home/egor/Work/codestyle/code/code2vec/dataset/idea-changes/changes_split_fixed/"
seed: 239
entities: [67,80,298,406,174,276,186,65,113,244,249,207,155,74,157,392,291,119,137,286,319,37,124,230,347,255]
contextsplit_depth: 10
features:
  - "paths"
  - "starts"
feature_count: 50000
random_contextsplit: True
params:
  n_estimators: 10
  n_jobs: -1
  min_samples_leaf: 1
  min_samples_split: 2
  max_features: 'sqrt'
  random_state: 239
