source_folder: "/home/egor/Work/authorship-detection/mining/gitminer/out/fresco"
classifier_type: "nn"
seed: 239
test_size: 0.1
epochs: 3
batch_size: 16
hidden_dim: 32
learning_rate: 0.01
min_count: 100
max_count: 1000
log_batches: 10
time_folds: 4