source_folder: "/home/egor/Work/authorship-detection/attribution/gitminer/out/gradle"
classifier_type: "caliskan"
seed: 239
mode: "context"
min_count: 100
feature_count: 2000
params:
  n_estimators: 100
  n_jobs: -1
  min_samples_leaf: 1
  min_samples_split: 2
  max_features: 'sqrt'
  random_state: 239

