source_folder: "/home/egor/Work/authorship-detection/mining/gitminer/out/fresco"
features:
  - "paths"
  - "starts"
  - "ends"
seed: 239
test_size: 0.1
min_count: 100
max_count: 1000
params:
  n_estimators: 100
  n_jobs: -1
  min_samples_leaf: 1
  min_samples_split: 2
  max_features: 'sqrt'
  random_state: 239
time_folds: 4