source_folder: "../processed/gcj"
features:
  - "starts"
  - "paths"
label_position: 4
seed: 239
test_size: 1
n_classes: 1600
params:
  n_estimators: 100
  n_jobs: -1
  min_samples_leaf: 1
  min_samples_split: 2
  max_depth: 10
  max_features: 'sqrt'
  random_state: 239