source_folder: "../processed/gcj"
mutual_info_file: "mutual_info/all_cpp_scores.numpy"
features:
  - "starts"
  - "paths"
label_position: 4
seed: 239
test_size: 1
n_classes: 1600
feature_count: 10000
params:
  n_estimators: 100
  n_jobs: -1
  min_samples_leaf: 1
  min_samples_split: 2
  max_features: 'sqrt'
  random_state: 239