source_folder: "/home/egor/Work/codestyle/code/code2vec/dataset/idea-changes/"
split_folder: "/home/egor/Work/codestyle/code/code2vec/dataset/idea-changes/creations/time_split/"
classifier_type: "nn"
seed: 239
epochs: 6
n_classes: 20
time_folds: 10
batch_size: 512
hidden_dim: 64
learning_rate: 0.01
log_batches: 10