source_folder: "../processed/java40"
features:
  - "explicit"
label_position: 3
seed: 239
test_size: 0.1
params:
  n_estimators: 100
  n_jobs: -1
  min_samples_leaf: 1
  min_samples_split: 2
  max_features: 'sqrt'
  random_state: 239