source_folder: ../../processed103/java40/java/
classifier_type: rf
mode: snapshot
features:
  - "paths"
  - "starts"
seed: 239
test_size: 0.1
feature_count: 2500
params:
  n_estimators: 500
  n_jobs: -1
  min_samples_leaf: 1
  min_samples_split: 2
  max_features: 'sqrt'
  random_state: 239