source_folder: ../../processed/java_antlr_8_2/java/
classifier_type: rf
mode: snapshot
features:
  - "paths"
  - "starts"
seed: 239
test_size: 0.1
feature_count: 5000
params:
  n_estimators: 400
  n_jobs: -1
  min_samples_leaf: 1
  min_samples_split: 2
  max_features: 'sqrt'
  random_state: 239