source_folder: ../../processed/gcj_joern_6_2/cpp/
classifier_type: rf
mode: snapshot
features:
  - "starts"
  - "paths"
seed: 239
test_size: 1
feature_count: 3000
params:
  n_estimators: 300
  n_jobs: -1
  min_samples_leaf: 1
  min_samples_split: 2
  max_features: 'sqrt'
  max_depth: 30
  random_state: 239
