classifier_type: caliskan
feature_count: 5000
max_count: 10000
min_count: 1000
mode: time
params:
  max_features: sqrt
  min_samples_leaf: 1
  min_samples_split: 2
  n_estimators: 300
  n_jobs: -1
  random_state: 239
seed: 239
source_folder: ../gitminer/out/gradle
time_folds: 10
